-- Requerida por StaffQueryBuilder para que el filtro de busqueda ignore tildes (ej. "ramir" encuentra
-- "Ramírez"). CREATE EXTENSION es idempotente por si sola, sin necesitar ON CONFLICT.
CREATE EXTENSION IF NOT EXISTS unaccent;

-- Catalogo gestionado por el sistema: se siembra aca y solo se consume via GET /platformStatuses.
-- El script corre en cada arranque; ON CONFLICT (sub_module, code) DO NOTHING lo hace idempotente.
-- code es unico por submodulo, no global: otros submodulos pueden reusar el mismo code (ej. ACTIVE).
INSERT INTO platform_status (name, code, description, sort_order, sub_module, active,
                             created_at, updated_at, created_by, updated_by)
VALUES
	('Planificado',  'PLANNED',      'Proyecto creado, aún no inicia en terreno.',   1, 'project', true, now(), now(), 'system', 'system'),
	('En ejecución', 'IN_PROGRESS',  'Proyecto en obra.',                            2, 'project', true, now(), now(), 'system', 'system'),
	('Suspendido',   'SUSPENDED',    'Proyecto detenido temporalmente.',             3, 'project', true, now(), now(), 'system', 'system'),
	('Finalizado',   'COMPLETED',    'Proyecto terminado.',                          4, 'project', true, now(), now(), 'system', 'system'),
	('Cancelado',    'CANCELLED',    'Proyecto cancelado antes de completarse.',     5, 'project', true, now(), now(), 'system', 'system'),
	('Pendiente de aprobación', 'PENDING_APPROVAL',  'Esperando aprobación de jefatura.',        1, 'request', true, now(), now(), 'system', 'system'),
	('Pendiente de validación', 'PENDING_VALIDATION', 'Aprobada por jefatura, esperando validación de RRHH.', 2, 'request', true, now(), now(), 'system', 'system'),
	('Aprobada',                'APPROVED',           'Validada por RRHH, cambios ya aplicados.', 3, 'request', true, now(), now(), 'system', 'system'),
	('Rechazada',               'REJECTED',           'Rechazada en algún nivel de aprobación.',  4, 'request', true, now(), now(), 'system', 'system'),
	('Pendiente de aprobación', 'PENDING_APPROVAL',   'Esperando aprobación de jefatura.',                    1, 'contract', true, now(), now(), 'system', 'system'),
	('Pendiente de validación', 'PENDING_VALIDATION', 'Aprobado por jefatura, esperando validación de RRHH.', 2, 'contract', true, now(), now(), 'system', 'system'),
	('Activo',                  'ACTIVE',              'Validado por RRHH, colaborador activo bajo este contrato.', 3, 'contract', true, now(), now(), 'system', 'system'),
	('Rechazado',               'REJECTED',            'Rechazado en algún nivel de aprobación.',              4, 'contract', true, now(), now(), 'system', 'system'),
	('Vencido',                 'EXPIRED',             'Llegó a su fecha de término sin renovarse.',           5, 'contract', true, now(), now(), 'system', 'system'),
	('Anulado',                 'ANNULLED',            'Anulado manualmente tras estar activo.',               6, 'contract', true, now(), now(), 'system', 'system'),
	('Error de sincronización', 'SYNC_ERROR',          'Falló la sincronización con el ERP de RRHH.',          7, 'contract', true, now(), now(), 'system', 'system')
ON CONFLICT (sub_module, code) DO NOTHING;

-- Catálogos de solo lectura para la ficha de Staff (HU-B23, extensión legal). Valores editables por
-- Karla: son datos de referencia, no una regla de negocio en si (salvo BANCO_ESTADO, usado por
-- StaffValidation para la regla de "Cuenta Rut").
INSERT INTO registered_sex (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Femenino',  'FEMALE',  true, now(), now(), 'system', 'system'),
	('Masculino', 'MALE',    true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO marital_status (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Soltero/a', 'SINGLE',    true, now(), now(), 'system', 'system'),
	('Casado/a',  'MARRIED',   true, now(), now(), 'system', 'system'),
	('Divorciado/a', 'DIVORCED', true, now(), now(), 'system', 'system'),
	('Viudo/a',   'WIDOWED',   true, now(), now(), 'system', 'system'),
	('Conviviente civil (AUC)', 'CIVIL_UNION', true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO nationality (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Chilena',      'CHL', true, now(), now(), 'system', 'system'),
	('Venezolana',   'VEN', true, now(), now(), 'system', 'system'),
	('Colombiana',   'COL', true, now(), now(), 'system', 'system'),
	('Peruana',      'PER', true, now(), now(), 'system', 'system'),
	('Haitiana',     'HTI', true, now(), now(), 'system', 'system'),
	('Boliviana',    'BOL', true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO education_level (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Educación básica',              'BASIC',      true, now(), now(), 'system', 'system'),
	('Educación media',               'HIGH_SCHOOL', true, now(), now(), 'system', 'system'),
	('Técnico nivel superior',        'TECHNICAL',  true, now(), now(), 'system', 'system'),
	('Educación universitaria',       'UNIVERSITY', true, now(), now(), 'system', 'system'),
	('Sin estudios',                  'NONE',       true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO afp (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('AFP Capital',    'CAPITAL',   true, now(), now(), 'system', 'system'),
	('AFP Cuprum',     'CUPRUM',    true, now(), now(), 'system', 'system'),
	('AFP Habitat',    'HABITAT',   true, now(), now(), 'system', 'system'),
	('AFP Modelo',     'MODELO',    true, now(), now(), 'system', 'system'),
	('AFP PlanVital',  'PLANVITAL', true, now(), now(), 'system', 'system'),
	('AFP ProVida',    'PROVIDA',   true, now(), now(), 'system', 'system'),
	('AFP Uno',        'UNO',       true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO health_system (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Fonasa',             'FONASA',      true, now(), now(), 'system', 'system'),
	('Isapre Banmédica',   'BANMEDICA',   true, now(), now(), 'system', 'system'),
	('Isapre Colmena',     'COLMENA',     true, now(), now(), 'system', 'system'),
	('Isapre Consalud',    'CONSALUD',    true, now(), now(), 'system', 'system'),
	('Isapre Cruz Blanca', 'CRUZ_BLANCA', true, now(), now(), 'system', 'system'),
	('Isapre Vida Tres',   'VIDA_TRES',   true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO bank (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('BancoEstado',        'BANCO_ESTADO', true, now(), now(), 'system', 'system'),
	('Banco de Chile',     'BANCO_CHILE',  true, now(), now(), 'system', 'system'),
	('Banco Santander',    'SANTANDER',    true, now(), now(), 'system', 'system'),
	('Banco BCI',          'BCI',          true, now(), now(), 'system', 'system'),
	('Scotiabank',         'SCOTIABANK',   true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

-- Requerida por los selectores GET /regions, /provincias, /comunas (ubicacion jerarquica de Staff).
-- Fuente: climoralesg/api-regiones-provincias-comunas-Chile (16 regiones, 56 provincias, 346 comunas,
-- verificado contra la DPA oficial). code = region_iso_3166_2 / codigo de provincia/comuna de la fuente.
INSERT INTO region (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Arica y Parinacota', 'CL-AP', true, now(), now(), 'system', 'system'),
	('Tarapacá', 'CL-TA', true, now(), now(), 'system', 'system'),
	('Antofagasta', 'CL-AN', true, now(), now(), 'system', 'system'),
	('Atacama', 'CL-AT', true, now(), now(), 'system', 'system'),
	('Coquimbo', 'CL-CO', true, now(), now(), 'system', 'system'),
	('Valparaíso', 'CL-VS', true, now(), now(), 'system', 'system'),
	('Región del Libertador Gral. Bernardo O''Higgins', 'CL-LI', true, now(), now(), 'system', 'system'),
	('Región del Maule', 'CL-ML', true, now(), now(), 'system', 'system'),
	('Región del Biobío', 'CL-BI', true, now(), now(), 'system', 'system'),
	('Región del Ñuble', 'CL-NB', true, now(), now(), 'system', 'system'),
	('Región de la Araucanía', 'CL-AR', true, now(), now(), 'system', 'system'),
	('Región de los Ríos', 'CL-LR', true, now(), now(), 'system', 'system'),
	('Región de los Lagos', 'CL-LL', true, now(), now(), 'system', 'system'),
	('Región Aisén del Gral. Carlos Ibañez del Campo', 'CL-AI', true, now(), now(), 'system', 'system'),
	('Región de Magallanes y de la Antártica Chilena', 'CL-MA', true, now(), now(), 'system', 'system'),
	('Región Metropolitana de Santiago', 'CL-RM', true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO provincia (name, code, active, region_id, created_at, updated_at, created_by, updated_by)
SELECT v.name, v.code, true, r.id, now(), now(), 'system', 'system'
FROM (VALUES
	('Arica', 'ap01', 'CL-AP'),
	('Parinacota', 'ap02', 'CL-AP'),
	('Iquique', 'ta01', 'CL-TA'),
	('Tamarugal', 'ta02', 'CL-TA'),
	('Antofagasta', 'an01', 'CL-AN'),
	('El Loa', 'an02', 'CL-AN'),
	('Tocopilla', 'an03', 'CL-AN'),
	('Copiapó', 'at01', 'CL-AT'),
	('Chañaral', 'at02', 'CL-AT'),
	('Huasco', 'at03', 'CL-AT'),
	('Elqui', 'co01', 'CL-CO'),
	('Choapa', 'co02', 'CL-CO'),
	('Limarí', 'co03', 'CL-CO'),
	('Valparaíso', 'vs01', 'CL-VS'),
	('Isla de Pascua', 'vs02', 'CL-VS'),
	('Los Andes', 'vs03', 'CL-VS'),
	('Petorca', 'vs04', 'CL-VS'),
	('Quillota', 'vs05', 'CL-VS'),
	('San Antonio', 'vs06', 'CL-VS'),
	('San Felipe de Aconcagua', 'vs07', 'CL-VS'),
	('Marga Marga', 'vs08', 'CL-VS'),
	('Cachapoal', 'li01', 'CL-LI'),
	('Cardenal Caro', 'li02', 'CL-LI'),
	('Colchagua', 'li03', 'CL-LI'),
	('Talca', 'ml01', 'CL-ML'),
	('Cauquenes', 'ml02', 'CL-ML'),
	('Curicó', 'ml03', 'CL-ML'),
	('Linares', 'ml04', 'CL-ML'),
	('Concepción', 'bi01', 'CL-BI'),
	('Arauco', 'bi02', 'CL-BI'),
	('Biobío', 'bi03', 'CL-BI'),
	('Diguillín', 'nb01', 'CL-NB'),
	('Itata', 'nb02', 'CL-NB'),
	('Punilla', 'nb03', 'CL-NB'),
	('Cautín', 'ar01', 'CL-AR'),
	('Malleco', 'ar02', 'CL-AR'),
	('Valdivia', 'lr01', 'CL-LR'),
	('Ranco', 'lr02', 'CL-LR'),
	('Llanquihue', 'll01', 'CL-LL'),
	('Chiloé', 'll02', 'CL-LL'),
	('Osorno', 'll03', 'CL-LL'),
	('Palena', 'll04', 'CL-LL'),
	('Coyhaique', 'ai01', 'CL-AI'),
	('Aysén', 'ai02', 'CL-AI'),
	('Capitán Pratt', 'ai03', 'CL-AI'),
	('General Carrera', 'ai04', 'CL-AI'),
	('Magallanes', 'ma01', 'CL-MA'),
	('Antártica Chilena', 'ma02', 'CL-MA'),
	('Tierra del Fuego', 'ma03', 'CL-MA'),
	('Última Esperanza', 'ma04', 'CL-MA'),
	('Santiago', 'rm01', 'CL-RM'),
	('Cordillera', 'rm02', 'CL-RM'),
	('Chacabuco', 'rm03', 'CL-RM'),
	('Maipo', 'rm04', 'CL-RM'),
	('Mellipilla', 'rm05', 'CL-RM'),
	('Talagante', 'rm06', 'CL-RM')
) AS v(name, code, region_code)
JOIN region r ON r.code = v.region_code
ON CONFLICT (code) DO NOTHING;

INSERT INTO comuna (name, code, active, provincia_id, created_at, updated_at, created_by, updated_by)
SELECT v.name, v.code, true, p.id, now(), now(), 'system', 'system'
FROM (VALUES
	('Arica', 'ap0101', 'ap01'),
	('Camarones', 'ap0102', 'ap01'),
	('Putre', 'ap0201', 'ap02'),
	('General Lagos', 'ap0202', 'ap02'),
	('Iquique', 'ta0101', 'ta01'),
	('Alto Hospicio', 'ta0102', 'ta01'),
	('Pozo Almonte', 'ta0201', 'ta02'),
	('Camiña', 'ta0202', 'ta02'),
	('Colchane', 'ta0203', 'ta02'),
	('Huara', 'ta0204', 'ta02'),
	('Pica', 'ta0205', 'ta02'),
	('Antofagasta', 'an0101', 'an01'),
	('Mejillones', 'an0102', 'an01'),
	('Sierra Gorda', 'an0103', 'an01'),
	('Taltal', 'an0104', 'an01'),
	('Calama', 'an0201', 'an02'),
	('Ollagüe', 'an0202', 'an02'),
	('San Pedro de Atacama', 'an0203', 'an02'),
	('Tocopilla', 'an0301', 'an03'),
	('María Elena', 'an0302', 'an03'),
	('Copiapó', 'at0101', 'at01'),
	('Caldera', 'at0102', 'at01'),
	('Tierra Amarilla', 'at0103', 'at01'),
	('Chañaral', 'at0201', 'at02'),
	('Diego de Almagro', 'at0202', 'at02'),
	('Vallenar', 'at0301', 'at03'),
	('Alto del Carmen', 'at0302', 'at03'),
	('Freirina', 'at0303', 'at03'),
	('Huasco', 'at0304', 'at03'),
	('La Serena', 'co0101', 'co01'),
	('Coquimbo', 'co0102', 'co01'),
	('Andacollo', 'co0103', 'co01'),
	('La Higuera', 'co0104', 'co01'),
	('Paiguano', 'co0105', 'co01'),
	('Vicuña', 'co0106', 'co01'),
	('Illapel', 'co0201', 'co02'),
	('Canela', 'co0202', 'co02'),
	('Los Vilos', 'co0203', 'co02'),
	('Salamanca', 'co0204', 'co02'),
	('Ovalle', 'co0301', 'co03'),
	('Combarbalá', 'co0302', 'co03'),
	('Monte Patria', 'co0303', 'co03'),
	('Punitaqui', 'co0304', 'co03'),
	('Río Hurtado', 'co0305', 'co03'),
	('Valparaíso', 'vs0101', 'vs01'),
	('Casablanca', 'vs0102', 'vs01'),
	('Concón', 'vs0103', 'vs01'),
	('Juan Fernández', 'vs0104', 'vs01'),
	('Puchuncaví', 'vs0105', 'vs01'),
	('Quintero', 'vs0107', 'vs01'),
	('Viña del Mar', 'vs0109', 'vs01'),
	('Isla de Pascua', 'vs0201', 'vs02'),
	('Los Andes', 'vs0301', 'vs03'),
	('Calle Larga', 'vs0302', 'vs03'),
	('Riconada', 'vs0303', 'vs03'),
	('San Esteban', 'vs0304', 'vs03'),
	('La Ligua', 'vs0401', 'vs04'),
	('Cabildo', 'vs0402', 'vs04'),
	('Papudo', 'vs0403', 'vs04'),
	('Petorca', 'vs0404', 'vs04'),
	('Zapallar', 'vs0405', 'vs04'),
	('Quillota', 'vs0501', 'vs05'),
	('Calera', 'vs0502', 'vs05'),
	('Hijuelas', 'vs0503', 'vs05'),
	('La Cruz', 'vs0504', 'vs05'),
	('Nogales', 'vs0506', 'vs05'),
	('San Antonio', 'vs0601', 'vs06'),
	('Algarrobo', 'vs0602', 'vs06'),
	('Cartagena', 'vs0603', 'vs06'),
	('El Quisco', 'vs0604', 'vs06'),
	('El Tabo', 'vs0605', 'vs06'),
	('Santo Domingo', 'vs0606', 'vs06'),
	('San Felipe', 'vs0701', 'vs07'),
	('Catemu', 'vs0702', 'vs07'),
	('Llaillay', 'vs0703', 'vs07'),
	('Panquehue', 'vs0704', 'vs07'),
	('Putaendo', 'vs0705', 'vs07'),
	('Santa María', 'vs0706', 'vs07'),
	('Quilpué', 'vs0801', 'vs08'),
	('Limache', 'vs0802', 'vs08'),
	('Olmué', 'vs0803', 'vs08'),
	('Villa Alemana', 'vs0804', 'vs08'),
	('Rancagua', 'li0101', 'li01'),
	('Codegua', 'li0102', 'li01'),
	('Coinco', 'li0103', 'li01'),
	('Coltauco', 'li0104', 'li01'),
	('Doñihue', 'li0105', 'li01'),
	('Graneros', 'li0106', 'li01'),
	('Las Cabras', 'li0107', 'li01'),
	('Machalí', 'li0108', 'li01'),
	('Malloa', 'li0109', 'li01'),
	('Mostazal', 'li0110', 'li01'),
	('Olivar', 'li0111', 'li01'),
	('Peumo', 'li0112', 'li01'),
	('Pichidegua', 'li0113', 'li01'),
	('Quinta de Tilcoco', 'li0114', 'li01'),
	('Rengo', 'li0115', 'li01'),
	('Requínoa', 'li0116', 'li01'),
	('San Vicente', 'li0117', 'li01'),
	('Pichilemu', 'li0201', 'li02'),
	('La Estrella', 'li0202', 'li02'),
	('Litueche', 'li0203', 'li02'),
	('Marichihue', 'li0204', 'li02'),
	('Navidad', 'li0205', 'li02'),
	('Paredones', 'li0206', 'li02'),
	('San Fernando', 'li0301', 'li03'),
	('Chépica', 'li0302', 'li03'),
	('Chimbarongo', 'li0303', 'li03'),
	('Lolol', 'li0304', 'li03'),
	('Nancagua', 'li0305', 'li03'),
	('Palmilla', 'li0306', 'li03'),
	('Peralillo', 'li0307', 'li03'),
	('Placilla', 'li0308', 'li03'),
	('Pumanque', 'li0309', 'li03'),
	('Santa Cruz', 'li0310', 'li03'),
	('Talca', 'ml0101', 'ml01'),
	('Constitución', 'ml0102', 'ml01'),
	('Curepto', 'ml0103', 'ml01'),
	('Empedrado', 'ml0104', 'ml01'),
	('Maule', 'ml0105', 'ml01'),
	('Pelarco', 'ml0106', 'ml01'),
	('Pencahue', 'ml0107', 'ml01'),
	('Río Claro', 'ml0108', 'ml01'),
	('San Clemente', 'ml0109', 'ml01'),
	('San Rafael', 'ml0110', 'ml01'),
	('Cauquenes', 'ml0201', 'ml02'),
	('Chanco', 'ml0202', 'ml02'),
	('Pelluhue', 'ml0203', 'ml02'),
	('Curicó', 'ml0301', 'ml03'),
	('Hualañé', 'ml0302', 'ml03'),
	('Licantén', 'ml0303', 'ml03'),
	('Molina', 'ml0304', 'ml03'),
	('Rauco', 'ml0305', 'ml03'),
	('Romeral', 'ml0306', 'ml03'),
	('Sagrada Familia', 'ml0307', 'ml03'),
	('Teno', 'ml0308', 'ml03'),
	('Vichuquén', 'ml0309', 'ml03'),
	('Linares', 'ml0401', 'ml04'),
	('Colbún', 'ml0402', 'ml04'),
	('Longaví', 'ml0403', 'ml04'),
	('Parral', 'ml0404', 'ml04'),
	('Retiro', 'ml0405', 'ml04'),
	('San Javier', 'ml0406', 'ml04'),
	('Villa Alegre', 'ml0407', 'ml04'),
	('Yerbas Buenas', 'ml0408', 'ml04'),
	('Concepción', 'bi0101', 'bi01'),
	('Coronel', 'bi0102', 'bi01'),
	('Chiguayante', 'bi0103', 'bi01'),
	('Florida', 'bi0104', 'bi01'),
	('Hualqui', 'bi0105', 'bi01'),
	('Lota', 'bi0106', 'bi01'),
	('Penco', 'bi0107', 'bi01'),
	('San Pedro de la Paz', 'bi0108', 'bi01'),
	('Santa Juana', 'bi0109', 'bi01'),
	('Talcahuano', 'bi0110', 'bi01'),
	('Tomé', 'bi0111', 'bi01'),
	('Hualpén', 'bi0112', 'bi01'),
	('Lebu', 'bi0201', 'bi02'),
	('Arauco', 'bi0202', 'bi02'),
	('Cañete', 'bi0203', 'bi02'),
	('Contulmo', 'bi0204', 'bi02'),
	('Curanilahue', 'bi0205', 'bi02'),
	('Los Álamos', 'bi0206', 'bi02'),
	('Tirúa', 'bi0207', 'bi02'),
	('Los Ángeles', 'bi0301', 'bi03'),
	('Antuco', 'bi0302', 'bi03'),
	('Cabrero', 'bi0303', 'bi03'),
	('Laja', 'bi0304', 'bi03'),
	('Mulchén', 'bi0305', 'bi03'),
	('Nacimiento', 'bi0306', 'bi03'),
	('Negrete', 'bi0307', 'bi03'),
	('Quilaco', 'bi0308', 'bi03'),
	('Quilleco', 'bi0309', 'bi03'),
	('San Rosendo', 'bi0310', 'bi03'),
	('Santa Bárbara', 'bi0311', 'bi03'),
	('Tucapel', 'bi0312', 'bi03'),
	('Yumbel', 'bi0313', 'bi03'),
	('Alto Biobío', 'bi0314', 'bi03'),
	('Bulnes', 'nb0101', 'nb01'),
	('Chillán', 'nb0102', 'nb01'),
	('Chillán Viejo', 'nb0103', 'nb01'),
	('El Carmen', 'nb0104', 'nb01'),
	('Pemuco', 'nb0105', 'nb01'),
	('Pinto', 'nb0106', 'nb01'),
	('Quillón', 'nb0107', 'nb01'),
	('San Ignacio', 'nb0108', 'nb01'),
	('Yungay', 'nb0109', 'nb01'),
	('Cobquecura', 'nb0201', 'nb02'),
	('Coelemu', 'nb0202', 'nb02'),
	('Ninhue', 'nb0203', 'nb02'),
	('Portezuelo', 'nb0204', 'nb02'),
	('Quirihue', 'nb0205', 'nb02'),
	('Ránquil', 'nb0206', 'nb02'),
	('Treguaco', 'nb0207', 'nb02'),
	('Coihueco', 'nb0301', 'nb03'),
	('Ñiquén', 'nb0302', 'nb03'),
	('San Carlos', 'nb0303', 'nb03'),
	('San Fabián', 'nb0304', 'nb03'),
	('San Nicolas', 'nb0305', 'nb03'),
	('Temuco', 'ar0101', 'ar01'),
	('Carahu', 'ar0102', 'ar01'),
	('Cunco', 'ar0103', 'ar01'),
	('Curarrehue', 'ar0104', 'ar01'),
	('Freire', 'ar0105', 'ar01'),
	('Galvarin', 'ar0106', 'ar01'),
	('Gorbea', 'ar0107', 'ar01'),
	('Lautaro', 'ar0108', 'ar01'),
	('Loncoche', 'ar0109', 'ar01'),
	('Melipeuco', 'ar0110', 'ar01'),
	('Nueva Imperial', 'ar0111', 'ar01'),
	('Padre las Casa', 'ar0112', 'ar01'),
	('Perquenco', 'ar0113', 'ar01'),
	('Pitrufquén', 'ar0114', 'ar01'),
	('Pucó', 'ar0115', 'ar01'),
	('Saavedra', 'ar0116', 'ar01'),
	('Teodoro Schmid', 'ar0117', 'ar01'),
	('Toltén', 'ar0118', 'ar01'),
	('Vilcún', 'ar0119', 'ar01'),
	('Villarrica', 'ar0120', 'ar01'),
	('Cholchol', 'ar0121', 'ar01'),
	('Angol', 'ar0201', 'ar02'),
	('Collipulli', 'ar0202', 'ar02'),
	('Curacautín', 'ar0203', 'ar02'),
	('Ercilla', 'ar0204', 'ar02'),
	('Lonquimay', 'ar0205', 'ar02'),
	('Los Sauces', 'ar0206', 'ar02'),
	('Lumaco', 'ar0207', 'ar02'),
	('Purén', 'ar0208', 'ar02'),
	('Renaico', 'ar0209', 'ar02'),
	('Traiguén', 'ar0210', 'ar02'),
	('Victoria', 'ar0211', 'ar02'),
	('Valdivia', 'lr0101', 'lr01'),
	('Corral', 'lr0102', 'lr01'),
	('Lanco', 'lr0103', 'lr01'),
	('Los Lagos', 'lr0104', 'lr01'),
	('Máfil', 'lr0105', 'lr01'),
	('Mariquina', 'lr0106', 'lr01'),
	('Paillaco', 'lr0107', 'lr01'),
	('Panguipulli', 'lr0108', 'lr01'),
	('La Unión', 'lr0201', 'lr02'),
	('Futrono', 'lr0202', 'lr02'),
	('Lago Ranco', 'lr0203', 'lr02'),
	('Río Bueno', 'lr0204', 'lr02'),
	('Puerto Montt', 'll0101', 'll01'),
	('Calbuco', 'll0102', 'll01'),
	('Cochamó', 'll0103', 'll01'),
	('Fresia', 'll0104', 'll01'),
	('Frutillar', 'll0105', 'll01'),
	('Los Muermos', 'll0106', 'll01'),
	('Llanquihue', 'll0107', 'll01'),
	('Maullín', 'll0108', 'll01'),
	('Puerto Varas', 'll0109', 'll01'),
	('Castro', 'll0201', 'll02'),
	('Ancud', 'll0202', 'll02'),
	('Chonchi', 'll0203', 'll02'),
	('Curaco de Vélez', 'll0204', 'll02'),
	('Dalcahue', 'll0205', 'll02'),
	('Puqueldón', 'll0206', 'll02'),
	('Queilén', 'll0207', 'll02'),
	('Quellón', 'll0208', 'll02'),
	('Quemchi', 'll0209', 'll02'),
	('Quinchao', 'll0210', 'll02'),
	('Osorno', 'll0301', 'll03'),
	('Puerto Octay', 'll0302', 'll03'),
	('Purranque', 'll0303', 'll03'),
	('Puyehue', 'll0304', 'll03'),
	('Río Negro', 'll0305', 'll03'),
	('San Juan de la Costa', 'll0306', 'll03'),
	('San Pablo', 'll0307', 'll03'),
	('Chaitén', 'll0401', 'll04'),
	('Futaleufú', 'll0402', 'll04'),
	('Hualaihué', 'll0403', 'll04'),
	('Palena', 'll0404', 'll04'),
	('Coyhaique', 'ai0101', 'ai01'),
	('Lago Verde', 'ai0102', 'ai01'),
	('Aisén', 'ai0201', 'ai02'),
	('Cisnes', 'ai0202', 'ai02'),
	('Guaitecas', 'ai0203', 'ai02'),
	('Cochrane', 'ai0301', 'ai03'),
	('O’Higgins', 'ai0302', 'ai03'),
	('Tortel', 'ai0303', 'ai03'),
	('Chile Chico', 'ai0401', 'ai04'),
	('Río Ibáñez', 'ai0402', 'ai04'),
	('Punta Arenas', 'ma0101', 'ma01'),
	('Laguna Blanca', 'ma0102', 'ma01'),
	('Río Verde', 'ma0103', 'ma01'),
	('San Gregorio', 'ma0104', 'ma01'),
	('Cabo de Hornos (Ex. Navarino)', 'ma0201', 'ma02'),
	('Antártica', 'ma0202', 'ma02'),
	('Porvenir', 'ma0301', 'ma03'),
	('Primavera', 'ma0302', 'ma03'),
	('Timaukel', 'ma0303', 'ma03'),
	('Natales', 'ma0401', 'ma04'),
	('Torres del Paine', 'ma0402', 'ma04'),
	('Santiago', 'rm0101', 'rm01'),
	('Cerrillos', 'rm0102', 'rm01'),
	('Cerro Navia', 'rm0103', 'rm01'),
	('Conchalí', 'rm0104', 'rm01'),
	('El Bosque', 'rm0105', 'rm01'),
	('Estación Central', 'rm0106', 'rm01'),
	('Huechuraba', 'rm0107', 'rm01'),
	('Independencia', 'rm0108', 'rm01'),
	('La Cisterna', 'rm0109', 'rm01'),
	('La Florida', 'rm0110', 'rm01'),
	('La Granja', 'rm0111', 'rm01'),
	('La Pintana', 'rm0112', 'rm01'),
	('La Reina', 'rm0113', 'rm01'),
	('Las Condes', 'rm0114', 'rm01'),
	('Lo Barnechea', 'rm0115', 'rm01'),
	('Lo Espejo', 'rm0116', 'rm01'),
	('Lo Prado', 'rm0117', 'rm01'),
	('Macul', 'rm0118', 'rm01'),
	('Maipú', 'rm0119', 'rm01'),
	('Ñuñoa', 'rm0120', 'rm01'),
	('Pedro Aguirre Cerda', 'rm0121', 'rm01'),
	('Peñalolén', 'rm0122', 'rm01'),
	('Providencia', 'rm0123', 'rm01'),
	('Pudahuel', 'rm0124', 'rm01'),
	('Quilicura', 'rm0125', 'rm01'),
	('Quinta Normal', 'rm0126', 'rm01'),
	('Recoleta', 'rm0127', 'rm01'),
	('Renca', 'rm0128', 'rm01'),
	('San Joaquín', 'rm0129', 'rm01'),
	('San Miguel', 'rm0130', 'rm01'),
	('San Ramón', 'rm0131', 'rm01'),
	('Vitacura', 'rm0132', 'rm01'),
	('Puente Alto', 'rm0201', 'rm02'),
	('Pirque', 'rm0202', 'rm02'),
	('San José de Maipo', 'rm0203', 'rm02'),
	('Colina', 'rm0301', 'rm03'),
	('Lampa', 'rm0302', 'rm03'),
	('Tiltil', 'rm0303', 'rm03'),
	('San Bernardo', 'rm0401', 'rm04'),
	('Buin', 'rm0402', 'rm04'),
	('Calera de Tango', 'rm0403', 'rm04'),
	('Paine', 'rm0404', 'rm04'),
	('Melipilla', 'rm0501', 'rm05'),
	('Alhué', 'rm0502', 'rm05'),
	('Curacaví', 'rm0503', 'rm05'),
	('María Pinto', 'rm0504', 'rm05'),
	('San Pedro', 'rm0505', 'rm05'),
	('Talagante', 'rm0601', 'rm06'),
	('El Monte', 'rm0602', 'rm06'),
	('Isla de Maipo', 'rm0603', 'rm06'),
	('Padre Hurtado', 'rm0604', 'rm06'),
	('Peñaflor', 'rm0605', 'rm06')
) AS v(name, code, provincia_code)
JOIN provincia p ON p.code = v.provincia_code
ON CONFLICT (code) DO NOTHING;

-- Catálogos de solo lectura para Contract (sin CRUD). Valores editables por Karla; JobTitle viene del
-- clasificador oficial CIUO-08-CL (INE), filtrado a ocupaciones de construcción/instalaciones.
INSERT INTO company (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Constructora Promaty S.A.', 'PROMATY', true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO contract_type (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Contrato indefinido',       'INDEFINIDO', true, now(), now(), 'system', 'system'),
	('Contrato a plazo fijo',     'FIJO',       true, now(), now(), 'system', 'system'),
	('Contrato por obra o faena', 'F',          true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO site (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Casa matriz (Santiago)',          'MATRIZ', true, now(), now(), 'system', 'system'),
	('Sucursal — Región de Valparaíso', 'VALPO',  true, now(), now(), 'system', 'system'),
	('Sucursal — Región de Antofagasta', 'ANTOFA', true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO meal_type (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Colación en efectivo', 'CASH',    true, now(), now(), 'system', 'system'),
	('Colación en especie',  'IN_KIND', true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO transport_type (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Movilización en efectivo',        'CASH',    true, now(), now(), 'system', 'system'),
	('Movilización pagada por la empresa', 'COMPANY_PAID', true, now(), now(), 'system', 'system'),
	('Sin movilización',                'NONE',    true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;

INSERT INTO job_title (name, code, active, created_at, updated_at, created_by, updated_by)
VALUES
	('Ingenieros civiles, ingenieros en construcción y constructores civiles', '2142', true, now(), now(), 'system', 'system'),
	('Ingenieros en prevención de riesgos y otros profesionales de la seguridad e higiene laboral y ambiental', '2243', true, now(), now(), 'system', 'system'),
	('Técnicos en construcción y topógrafos', '3112', true, now(), now(), 'system', 'system'),
	('Técnicos en electricidad', '3113', true, now(), now(), 'system', 'system'),
	('Supervisores de la construcción', '3123', true, now(), now(), 'system', 'system'),
	('Inspectores de la salud y técnicos en prevención de riesgos', '3257', true, now(), now(), 'system', 'system'),
	('Empleados encargados del control de abastecimiento e inventario', '4321', true, now(), now(), 'system', 'system'),
	('Albañiles', '7112', true, now(), now(), 'system', 'system'),
	('Tronzadores, labrantes y grabadores de piedra', '7113', true, now(), now(), 'system', 'system'),
	('Operarios en cemento armado', '7114', true, now(), now(), 'system', 'system'),
	('Carpinteros de obra', '7115', true, now(), now(), 'system', 'system'),
	('Otros operarios de la construcción (obra gruesa) no clasificados previamente', '7119', true, now(), now(), 'system', 'system'),
	('Instaladores o reparadores de techos', '7121', true, now(), now(), 'system', 'system'),
	('Instaladores de parqué, cerámicas, baldosas y alfombras', '7122', true, now(), now(), 'system', 'system'),
	('Yeseros, estucadores y revocadores', '7123', true, now(), now(), 'system', 'system'),
	('Instaladores de material aislante y de insonorización', '7124', true, now(), now(), 'system', 'system'),
	('Cristaleros', '7125', true, now(), now(), 'system', 'system'),
	('Gásfiter e instaladores de tuberías', '7126', true, now(), now(), 'system', 'system'),
	('Mecánicos de instalaciones de refrigeración y aire acondicionado', '7127', true, now(), now(), 'system', 'system'),
	('Pintores y empapeladores de paredes', '7131', true, now(), now(), 'system', 'system'),
	('Barnizadores y pulverizadores de productos manufacturados', '7132', true, now(), now(), 'system', 'system'),
	('Limpiadores de fachadas y deshollinadores', '7133', true, now(), now(), 'system', 'system'),
	('Moldeadores y macheros', '7211', true, now(), now(), 'system', 'system'),
	('Soldadores y oxicortadores', '7212', true, now(), now(), 'system', 'system'),
	('Chapistas y caldereros', '7213', true, now(), now(), 'system', 'system'),
	('Montadores de estructuras metálicas', '7214', true, now(), now(), 'system', 'system'),
	('Aparejadores y empalmadores de cables no eléctricos', '7215', true, now(), now(), 'system', 'system'),
	('Electricistas de obras', '7411', true, now(), now(), 'system', 'system'),
	('Mecánicos y ajustadores electricistas', '7412', true, now(), now(), 'system', 'system'),
	('Conductores de camiones pesados y de alto tonelaje', '8332', true, now(), now(), 'system', 'system'),
	('Operadores de grúas y aparatos elevadores', '8343', true, now(), now(), 'system', 'system')
ON CONFLICT (code) DO NOTHING;
